name: code_streak
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.10

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  go_router: ^14.3.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  injectable: ^2.1.1
  json_annotation: ^4.8.1
  github: ^9.24.0
  flutter_dotenv: ^5.1.0
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  appwrite: 13.0.0
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1
  skeletonizer: ^1.4.2
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  accordion_sliver_app_bar: ^0.0.2
  mobile_device_identifier: ^0.0.3
  convert: ^3.1.2
  crypto: ^3.0.6
  custom_refresh_indicator: ^4.0.1
  package_info_plus: ^8.1.3
  lottie: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  freezed: ^2.4.7
  json_serializable: ^6.8.0
  injectable_generator: ^2.1.5
  flutter_gen_runner: ^5.8.0


flutter_gen:
  # Optional
  integrations:
    flutter_svg: true
    # lottie: true

flutter:
  generate: true
  uses-material-design: true


  assets:
    - assets/
    - assets/images/
    - assets/jsons/
